library(MCMCglmm)
random=NULL
rcov=~units
family="gaussian"
mev=NULL
start=NULL
prior=NULL
tune=NULL
pedigree=NULL
nodes="ALL"
scale=TRUE
nitt=13000
thin=10
burnin=3000
pr=FALSE
pl=FALSE
verbose=TRUE
DIC=TRUE
singular.ok=FALSE
source("~/Work/AManal/MCMCglmm_1.12/R/MCMCglmm.R")
source("~/Work/AManal/MCMCglmm_1.12/R/split.direct.sum.R")
source("~/Work/AManal/MCMCglmm_1.12/R/buildZ.R")
source("~/Work/AManal/MCMCglmm_1.12/R/find.components.R")
